name: collegeapplication
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  intl: ^0.18.0
  uuid: ^4.0.0
  cupertino_icons: ^1.0.6
  google_mlkit_text_recognition: 0.11.0
  image_picker: ^1.1.2
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  camera: ^0.10.5
  image: ^4.1.7
  image_cropper: ^5.0.1
  google_mlkit_document_scanner: 0.9.0
  pdf: ^3.10.8
  firebase_storage: ^11.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
