
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd1Q03_edrlHL4yNKT1Wjf3Bz0VvEh5q8',
    appId: '1:748847751585:web:bb7b995ea3b43db9e62be0',
    messagingSenderId: '748847751585',
    projectId: 'smartdoc-9f672',
    authDomain: 'smartdoc-9f672.firebaseapp.com',
    storageBucket: 'smartdoc-9f672.firebasestorage.app',
    measurementId: 'G-ZLYCVW8BER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUgprDAtNzGLGXKY4gnPO45x1vh0IjLBU',
    appId: '1:748847751585:android:79428ec061e0ce88e62be0',
    messagingSenderId: '748847751585',
    projectId: 'smartdoc-9f672',
    storageBucket: 'smartdoc-9f672.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIyA1sk0AK9fewfzkXcbtd9ilOJM1rxOA',
    appId: '1:748847751585:ios:8043c5bddff9959fe62be0',
    messagingSenderId: '748847751585',
    projectId: 'smartdoc-9f672',
    storageBucket: 'smartdoc-9f672.firebasestorage.app',
    iosBundleId: 'com.example.collegeapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIyA1sk0AK9fewfzkXcbtd9ilOJM1rxOA',
    appId: '1:748847751585:ios:8043c5bddff9959fe62be0',
    messagingSenderId: '748847751585',
    projectId: 'smartdoc-9f672',
    storageBucket: 'smartdoc-9f672.firebasestorage.app',
    iosBundleId: 'com.example.collegeapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd1Q03_edrlHL4yNKT1Wjf3Bz0VvEh5q8',
    appId: '1:748847751585:web:529cf24dd5f7ee1be62be0',
    messagingSenderId: '748847751585',
    projectId: 'smartdoc-9f672',
    authDomain: 'smartdoc-9f672.firebaseapp.com',
    storageBucket: 'smartdoc-9f672.firebasestorage.app',
    measurementId: 'G-MR9410TC3N',
  );

}